### ISSUE TITLE
推荐一个视频播放软件Source Player

### ISSUE THREAD

**Issue by suliveevil** [hzlzh/Best-App#112]
Source Player Lite（Pro收费98），可以在Mac App Store下载安装
免费版足够用了，配合三指查询Apple词典简直无敌
[截图](https://github.com/suliveevil/ultimate-macOS/blob/master/Resources/Source%20Player/define-word.png)

**Comment by larrylu** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by yifire** [comment]
你好，你的来信我已收到，我会尽快查看并回复你。谢谢，辛苦了！
