### ISSUE TITLE
Taskade 在家工作的实时组织和协作工具

### ISSUE THREAD

**Issue by johnxie** [hzlzh/Best-App#118]
Hi there,

I'd love to have Taskade included in the list. Can I send a pull request?

Taskade is a 在家工作的实时组织和协作工具 — a realtime organization and collaboration tool for managing tasks, writing notes, and video chatting in one unified workspace.

Our Mac App: https://apps.apple.com/us/app/taskade-manage-anything/id1490048917
Our iOS App: https://itunes.apple.com/us/app/taskade-checklist-outliner/id1264713923

Thank you. ✌️

**Comment by hzlzh** [comment]
抱歉，更为垂直类的工具会比较合适作为推荐，协作和 GTD 具有强烈的个人色彩。
