### ISSUE TITLE
推荐国人macOS剪贴板增强器FastClip

### ISSUE THREAD

**Issue by shenruisi** [hzlzh/Best-App#122]
[App Store 地址](https://apps.apple.com/cn/app/fastclip-endless-clipboard/id1476085650?l=en&mt=12)

[评测链接](https://creatorsdaily.com/posts/de3a5c63-d527-4c6d-81d3-2297b3fd7178)

[产品介绍链接](https://zhuanlan.zhihu.com/p/114253010)

**Comment by evaabion** [comment]
I just wanna ask how it can be done. Either for any tool or [game](https://telecombit.com/gta-5-ios-download/).
