### ISSUE TITLE
错误的License链接

### ISSUE THREAD

**Issue by gaomd** [hzlzh/Best-App#38]
mit-license.org 这个网站是需要 fork 后提交自己的 subdomain 的，我发现当前项目里都连接到了 rem.mit-license.org 这个网址，这是 Remy Sharp 个人的 License 申明页面，所以当前项目应该专门申请一个 subdomain，或者在根目录放一个 LICENSE 文件更直接点。

**Comment by gaomd** [comment]
Nevermind.

**Comment by hzlzh** [comment]
没关系，这两种都可以的，可以在 repo 下直接加一个授权文件

**Comment by gaomd** [comment]
因为这个链接的 Copyright 信息是不对的：rem.mit-license.org，这才是重点。
