### ISSUE TITLE
免费好用的OSX软件

### ISSUE THREAD

**Issue by zlkent** [hzlzh/Best-App#57]
Caffeine 禁止系统进入屏保和休眠状态
BetterTouchTool 触摸板手势自定义，键盘自定义，苹果遥控器自定义，苹果鼠标自定义的强大软件

**Comment by zhuxiaoxi** [comment]
Caffeine的界面像上个世纪的作品。最近发现了这个，很不错https://github.com/newmarcel/KeepingYouAwake
