### ISSUE TITLE
Typora markdown里面的佼佼者

### ISSUE THREAD

**Issue by runsunlife** [hzlzh/Best-App#66]
用了好几个markdown编辑器觉得这个很棒

**Comment by xirong** [comment]
而且不是「两栏」设计，实时展示最终的结果，mac 版本很流畅，已经添加到我的 [Markdown 收藏](https://github.com/xirong/my-markdown#markdown-工具)。

**Comment by iDvel** [comment]
第一次体验单栏书写markdown的快感，太棒了！

**Comment by runsunlife** [comment]
这个app还支持emoji呢。觉得特别好玩。

**Comment by lfkdsk** [comment]
试用之后，果然不凡，双栏设计造成的输入框狭小、预览框反复刷新被完全解决了

**Comment by kaito-kidd** [comment]
试过之后感觉很拉风啊，快捷键和格式提供的很方便！

**Comment by hzlzh** [comment]
试了一下，还不错

**Comment by runsunlife** [comment]
哈哈必须的就是字写多了还是会卡，估计是直接显示结果的事吧。我自己也很喜欢App和电子产品，挺喜欢按场景去找软件。自己也写了个[App-Choose](https://github.com/runsunlife/App-Choose) 没有您的那么专业。如果觉得写的可以的话 大神帮忙推荐下。
