### ISSUE TITLE
有些软件的价格发生了变动

### ISSUE THREAD

**Issue by winddweb** [hzlzh/Best-App#67]
价格变了，作者打算更新不？

比如我点了几个感兴趣的软件进去看，Timing 现在 $19.99，Ember $25（App Store $32 而且评价跌至谷底）

**Comment by jerryshew** [comment]
@winddweb  可以给作者发 pr， 虽然价格变动不会太及时。。。

**Comment by winddweb** [comment]
@jerryshew 嗯……OK

**Comment by winddweb** [comment]
#68 created
