### ISSUE TITLE
求问 列表还在维护吗？

### ISSUE THREAD

**Issue by YohannFree** [hzlzh/Best-App#84]
看到很多不管是付费应用还是免费应用或者下面的打折限免连接，里面的信息都变更了。求问，这个列表是否还在维护？

**Comment by hzlzh** [comment]
在维护的，我来排查一遍，另外如果有需要勘误的变动，你可以直接修改合并

**Comment by hkongm** [comment]
mac基本都是老软件，一鸣惊人的新软还是很少，生态很稳定了

**Comment by hzlzh** [comment]
是的，特别是效率工具类别，基本上已经完善了
