### ISSUE TITLE
推荐二次验证应用 Authy

### ISSUE THREAD

**Issue by xiaooloong** [hzlzh/Best-App#90]
https://play.google.com/store/apps/details?id=com.authy.authy

统一管理二次验证动态密码。自动同步备份。定期提示记忆加密密码。

**Comment by iamWangJunjie** [comment]
URL Scheme 打开各种闪退, 如果不是当时搬过去的时候已经费尽力气, 真的是打算换回去.

**Comment by byicer** [comment]
二次验证为什么不直接用Google Authentication呢？

**Comment by elvis-macak** [comment]
enpass也还好，PC上免费，往往是记个password顺便记下2fa

**Comment by xiaooloong** [comment]
@byicer 能同步二次验证配置。以前出现过手机刷机完登录账号时要求二次验证密码，结果手机上的软件数据早都没了。差点死循环。

**Comment by byicer** [comment]
@xiaooloong 你说得好有道理，这种情况下账户如果也没有一次性恢复验证码就是灾难~

**Comment by elephi** [comment]
我本来也在费尽心机找一个合适的Google Auth的替代品，最后发现我自己买的 1-Password 自带此功能。爽死了。

**Comment by maemual** [comment]
@elephi 把二次验证和密码都放到同一个 APP，不就失去了二次验证的意义了么。我用 Authy + 1Password

**Comment by hzlzh** [comment]
Google Auth 很难用，丢失就杯具。
我用 Authy App 安全

**Comment by iamWangJunjie** [comment]
说起来, Authy 在 Apple Watch 上还是挺好用的. 随着版本迭代, 原来的闪退问题也修复了. 
 
1Password 上真心不建议把关联账号直接配它的一次性密码功能, 否则很容易被一锅端. 特别是某些 1Password 用盗版的.

**Comment by elephi** [comment]
@iamWangJunjie @maemual 我用正版 1Password 很多年了，而且不用Windows，我对自己的 1Password 也保护得很好，因此我觉得对我来说安全系数还是很高的。

**Comment by rengs** [comment]
authy能同步到不同的机器上，很方便，google的丢了真的就麻烦了。

**Comment by hzlzh** [comment]
@rengs 我有一次新手机更换的时候丢了一次 token，从此不再用 google auth，坑我不浅。
