### ISSUE TITLE
iOS视频加速工具“10秒视频”，朋友圈视频不再受10秒时间限制！

### ISSUE THREAD

**Issue by ethansayhello** [hzlzh/Best-App#93]
10秒视频是一款视频加速工具，可以一键将视频时长加速至10秒，手机里的长视频加速之后可以直接发送朋友圈了~

视频加速后看起来完全不一样噢，发挥你的创意，玩转朋友圈，收获更多的赞吧！

下载地址：https://itunes.apple.com/cn/app/id1206242887

**Comment by MarioHoH** [comment]
coll!

**Comment by vvtommy** [comment]
bug 一大堆
